---
# tasks file for db
- name: install mysql
  apt: name={{ item }} state=present
  with_items: 
   - mysql-server 
   - python-mysqldb

- name: template config file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: restart mysql

- name: start and chkconfig mysql service on
  service: name=mysql state=started enabled=yes

- name: create the db
  mysql_db: name=ciscoapp state=present

- name: 
  mysql_user: name=dfed password=12345 priv=*.*:ALL,GRANT state=present